# Generated by Django 4.2.7 on 2024-01-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0004_message_send_alter_message_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.TextField(unique=True, verbose_name='Имя пользователя'),
        ),
    ]
